### ISSUE TITLE
Add Blackfire PHP extension

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox-engine-php#35]
It would be essential for profiling to have [Blackfire](https://blackfire.io/) available within Nanobox. This would mean that one can add `blackfire` to the `extensions` and configure client and server credentials.

**Comment by notxarb** [comment]
the blackfire extension should be available now.

**Comment by mbrodala** [comment]
Thanks, can you add it to the [list of extensions](http://guides.nanobox.io/php/generic/php-extensions/)?

Also I've tried modifying my `boxfile.yml` accordingly:

```yaml
run.config:
  engine.config:
    extensions:
      - blackfire
  dev_packages:
    - blackfire
```

I can see the packages being installed on `nanobox run`, however afterwards I don't see Blackfire anywhere, neither the module nor the CLI tool. Am I missing something?
