### ISSUE TITLE
`start-apache` with mod_php fails

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-engine-php#49]
boxfile:
```yaml
run.config:
  engine: php
  engine.config:
    runtime: php-7.0
    webserver: apache
    apache_php_interpreter: mod_php
```

error:
```
/app $ start-apache 
cp: cannot stat '/php/dev_php.ini': No such file or directory
ln: failed to create symbolic link '/php.d': Permission denied
httpd: Syntax error on line 33 of /data/etc/httpd/httpd.conf: Cannot load /data/lib/httpd/mod_php5.so into server: /data/lib/httpd/mod_php5.so: cannot open shared object file: No such file or directory
```

also, shouldn't it be mod_php7.so in the error?
