### ISSUE TITLE
Any folder named vendor will be ignored when deployed

### ISSUE THREAD

**Issue by Anthonyzou** [nanobox-io/nanobox-engine-php#86]
For some reason any subfolders in the project named `vendor` will not be included in the final deployment

**Comment by danhunsaker** [comment]
Do you have
```yaml
run.config:
  ...
  cache_dirs:
    - vendor
```
in your Boxfile? The PHP engine adds `/vendor` to this list automatically, so you don't need to add it yourself.
