### ISSUE TITLE
memory_limit rejecting value of -1

### ISSUE THREAD

**Issue by notxarb** [nanobox-io/nanobox-engine-php#88]
The php documentation states that setting the memory_limit to -1 basically set the limit to unlimited. The validation that the engine does doesn't allow for a value of -1 to be passed into the php.ini.

**Comment by pablorsk** [comment]
Please, try to doing this:

```yaml
[...]
run.config:
  engine: php
  engine.config:
    runtime: php-7.1
    memory_limit: '-1'
```

Then, if you check, memory was is not setted now

```bash
nanobox run php --info | grep memory_limit
memory_limit => no value => no value
```
