### ISSUE TITLE
PHP 7.0 broken composer

### ISSUE THREAD

**Issue by pablorsk** [nanobox-io/nanobox-engine-php#96]
Error:

**Comment by pablorsk** [comment]
Temporary solved with

```yaml
run.config:
  engine: nanobox-io/nanobox-engine-php
  engine.config:
    runtime: php-7.0
```
