### ISSUE TITLE
composer_install boxfile option dont work

### ISSUE THREAD

**Issue by pablorsk** [nanobox-io/nanobox-engine-php#97]
boxfile.yml:

```yaml
run.config:
  engine: php
  composer_install: "composer install --no-interaction --no-dev"
  engine.config:
    runtime: php-7.1
    document_root: public
[...]
```
Next, we run `nanobox run` and do `ls vendor/`: ALL DEV LIBRARIES ARE INSTALLED.

### Extra info
* No `extra_steps` are defined.
* `nanobox update-images` was runned before.

**Comment by pablorsk** [comment]
My mistake. Correct `yaml`:
```
run.config:
  engine: php
  engine.config:
    runtime: php-7.1
    composer_install: "composer install --no-interaction --no-dev"
    document_root: public
[...]
```
