### ISSUE TITLE
dev_extensions are installed, but composer doesn't detect them

### ISSUE THREAD

**Issue by pablorsk** [nanobox-io/nanobox-engine-php#98]
```yaml
# boxfile.yml
run.config:
  engine: php
  engine.config:
    runtime: php-7.1
    composer_install: "composer install --no-interaction"
    extensions:
      - curl
      - fileinfo
      - gd
      # [...]
    dev_extensions:
      add:
        - iconv
        # [...]
 # [...]
```

Then, `nanobox run -vvv`

```
Building runtime :
  Starting docker container :
  Preparing environment for build :
  [...]
  Installing binaries and runtimes :
    - Installing packages :
      [...]
      downloading packages...
      libunistring-0.9.7.tgz              100% 1416KB 708.0KB/s 603.9KB/s   00:02    
      xmlcatmgr-2.2nb1.tgz                100%   29KB  28.7KB/s  28.7KB/s   00:00    
      php71-iconv-7.1.17.tgz              100%   22KB  21.7KB/s  21.7KB/s   00:00    
      [...]
      installing php71-iconv-7.1.17...
      installing php71-dom-7.1.17...
      installing php71-simplexml-7.1.17...
      [...]

    Loading composer repositories with package information
    Installing dependencies (including require-dev) from lock file
    Your requirements could not be resolved to an installable set of packages.
    
      Problem 1
        - Installation request for nette/neon v2.4.2 -> satisfiable by nette/neon[v2.4.2].
        - nette/neon v2.4.2 requires ext-iconv * -> the requested PHP extension iconv is missing from your system.
      [...]
```
If we follow log of nanobox run, it's possible to see download and installation of ext-iconv, but when composer try to use it, don't work.

:bulb: If `dev_dependecies` moved to `dependencies`, `composer install` work fine! :confused:
